# 服务器配置
server:
  address: ":8888" # Hertz 监听地址和端口

# 数据库配置
database:
  neo4j:
    uri: "neo4j://localhost:7687" # Neo4j Bolt URI
    username: "neo4j"             # Neo4j 用户名
    password: "password"          # Neo4j 密码
  redis:
    addr: "localhost:6381"        # Redis 地址
    password: ""                  # Redis 密码 (如果需要)
    db: 0                         # Redis 数据库编号

# 缓存配置
cache:
  prefix: "labelwall:"            # Redis 缓存键前缀
  estimated_keys: 1000000          # 预估键数量 (用于布隆过滤器等)
  fp_rate: 0.01                   # 允许的误判率 (用于布隆过滤器等)
  ttl:                            # 缓存过期时间 (秒)
    default_node: 3600            # 节点默认 TTL (1 小时)
    default_relation: 1800        # 关系默认 TTL (30 分钟)
    search_nodes: 300             # 节点搜索结果 TTL (5 分钟)
    get_network: 3600              # 网络图谱结果 TTL (60 分钟)
    get_path: 900                 # 路径查询结果 TTL (15 分钟)
    get_node_relations: 300       # 节点关系列表 TTL (5 分钟)
    # 注意：空值/占位符的 TTL 通常较短，由 cache 包内部定义或在此单独配置
    # empty_placeholder: 60       # 示例：空占位符 TTL (1 分钟)

# 仓库层配置
repository:
  query_params:
    get_network_max_depth: 15      # GetNetwork 查询的最大深度限制
    get_path_max_depth: 30         # GetPath 查询的最大深度限制 (默认值)
    get_path_max_depth_limit: 100  # GetPath 查询的最大深度硬限制
    search_nodes_default_limit: 10 # SearchNodes 默认分页大小
    get_node_relations_default_limit: 10 # GetNodeRelations 默认分页大小

# 日志配置 (示例，可以根据需要扩展)
logging:
  level: "info"                   # 日志级别 (debug, info, warn, error) 
