global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'hertz_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['172.17.0.1:9091']
        # 确保 Hertz 应用的 metrics 服务监听在 Prometheus 可访问的接口。

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']
