// Code generated by hertz generator.

package network

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnetworkMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpathMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnodedetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nodesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createnodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletenodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatenodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _node_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnoderelationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createrelationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleterelationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrelationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updaterelationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _nodes0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchnodesMw() []app.HandlerFunc {
	// your code...
	return nil
}
